## Part 2: Practical Challenge (45–60 min)

### Scenario: "The May Export Audit"

The owner was impressed with your June clean-up and has sent the **May** export. It is a different
extract from the same till system, so it has the same *kinds* of problems in different places.

Start a new notebook in `notebooks/` and paste this in:

In [48]:
import pandas as pd
import numpy as np

may = pd.DataFrame({
    "outlet": ["Raffles Place", "raffles place", "RAFFLES PLACE", "Raffles Pl.",
               "Marina Bay", "marina bay", "Marina Bay ", "Marina Bay",
               "Tampines Mall", "tampines mall", "Holland Village", "Holland V"],
    "date_text": ["01/05/2025", "01/05/2025", "02/05/2025", "02/05/2025",
                  "01/05/2025", "01/05/2025", "02/05/2025", "02/05/2025",
                  "01/05/2025", "02/05/2025", "01/05/2025", "02/05/2025"],
    "daypart": ["Morning", "AM", "morning", "Midday",
                "Lunch", "midday", "Evening", "PM",
                "evening", "Morning", "AM", "Lunch"],
    "revenue_raw": ["S$612.40", " 318.75 ", "-999", "487.10",
                    "S$1,204.60", "296.55", "", "58000",
                    "S$734.20", "421.85", "S$389.90", "-999"],
    "tickets": [74, 39, 55, 58, 141, 36, 21, 112, 88, 51, np.nan, -3],
    "staff_on_shift": [3, 2, np.nan, 2, 5, 2, 1, 4, 4, 2, 2, np.nan],
    "manager": ["  Aisha Rahman ", "aisha rahman", "AISHA RAHMAN", "  Aisha Rahman",
                "Priya  Nair", "priya nair", "Priya Nair ", "Priya Nair",
                "wei ming tan", "Wei Ming Tan", "DANIEL LIM ", "Daniel Lim"],
    "notes": ["", "n/a", "N.A.", "-", "aircon down", "", "-", "", "n/a", "", "N.A.", ""],
})

may

,outlet,date_text,daypart,revenue_raw,tickets,staff_on_shift,manager,notes
0,Raffles Place,01/05/2025,Morning,S$612.40,74.0,3.0,Aisha Rahman,
1,raffles place,01/05/2025,AM,318.75,39.0,2.0,aisha rahman,n/a
2,RAFFLES PLACE,02/05/2025,morning,-999,55.0,NaN,AISHA RAHMAN,N.A.
3,Raffles Pl.,02/05/2025,Midday,487.10,58.0,2.0,Aisha Rahman,-
4,Marina Bay,01/05/2025,Lunch,"S$1,204.60",141.0,5.0,Priya Nair,aircon down
5,marina bay,01/05/2025,midday,296.55,36.0,2.0,priya nair,
6,Marina Bay,02/05/2025,Evening,,21.0,1.0,Priya Nair,-
7,Marina Bay,02/05/2025,PM,58000,112.0,4.0,Priya Nair,
8,Tampines Mall,01/05/2025,evening,S$734.20,88.0,4.0,wei ming tan,n/a
9,tampines mall,02/05/2025,Morning,421.85,51.0,2.0,Wei Ming Tan,
10,Holland Village,01/05/2025,AM,S$389.90,NaN,2.0,DANIEL LIM,N.A.
11,Holland V,02/05/2025,Lunch,-999,-3.0,NaN,Daniel Lim,

### Challenge 1: The Health Check

**Tasks:**
1. Run the five-move first look: `.head()`, `.shape`, `.info()`, `.dtypes`, `.describe()`.
2. Which column is missing from `.describe()` output, and why?
3. Use `.isna().sum()` to count missing values per column. Then look at `notes` with
   `.value_counts(dropna=False)` — how many values *look* empty but are not?
4. How many distinct outlets does pandas think there are? How many are there really?

In [49]:
display(may)

print(may.shape)

may.info()

may.describe()  ## revenue_raw is excluded this column is classified as text

,outlet,date_text,daypart,revenue_raw,tickets,staff_on_shift,manager,notes
0,Raffles Place,01/05/2025,Morning,S$612.40,74.0,3.0,Aisha Rahman,
1,raffles place,01/05/2025,AM,318.75,39.0,2.0,aisha rahman,n/a
2,RAFFLES PLACE,02/05/2025,morning,-999,55.0,NaN,AISHA RAHMAN,N.A.
3,Raffles Pl.,02/05/2025,Midday,487.10,58.0,2.0,Aisha Rahman,-
4,Marina Bay,01/05/2025,Lunch,"S$1,204.60",141.0,5.0,Priya Nair,aircon down
5,marina bay,01/05/2025,midday,296.55,36.0,2.0,priya nair,
6,Marina Bay,02/05/2025,Evening,,21.0,1.0,Priya Nair,-
7,Marina Bay,02/05/2025,PM,58000,112.0,4.0,Priya Nair,
8,Tampines Mall,01/05/2025,evening,S$734.20,88.0,4.0,wei ming tan,n/a
9,tampines mall,02/05/2025,Morning,421.85,51.0,2.0,Wei Ming Tan,
10,Holland Village,01/05/2025,AM,S$389.90,NaN,2.0,DANIEL LIM,N.A.
11,Holland V,02/05/2025,Lunch,-999,-3.0,NaN,Daniel Lim,

(12, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   outlet          12 non-null     object
 1   date_text       12 non-null     object
 2   daypart         12 non-null     object
 3   revenue_raw     12 non-null     object
 4   tickets         11 non-null     float64
 5   staff_on_shift  10 non-null     float64
 6   manager         12 non-null     object
 7   notes           12 non-null     object
dtypes: float64(2), object(6)
memory usage: 896.0+ bytes

          tickets  staff_on_shift
count   11.000000       10.000000
mean    61.090909        2.700000
std     41.047423        1.251666
min     -3.000000        1.000000
25%     37.500000        2.000000
50%     55.000000        2.000000
75%     81.000000        3.750000
max    141.000000        5.000000

In [50]:
print("\nmissing per column:")
print(may.isna().sum())

print("\nnotes, including the fake blanks:")
print(may["notes"].value_counts(dropna=False))

missing per column:
outlet            0
date_text         0
daypart           0
revenue_raw       0
tickets           1
staff_on_shift    2
manager           0
notes             0
dtype: int64

notes, including the fake blanks:
               5
n/a            2
N.A.           2
-              2
aircon down    1
Name: notes, dtype: int64

In [51]:
print("\noutlets pandas sees:", may["outlet"].nunique(), "vs real cafés: 4")

may["outlet"].unique()  # .unique() list the distinct records | .nunique() count the distinct records

outlets pandas sees: 11 vs real cafés: 4

array(['Raffles Place', 'raffles place', 'RAFFLES PLACE', 'Raffles Pl.',
       'Marina Bay', 'marina bay', 'Marina Bay ', 'Tampines Mall',
       'tampines mall', 'Holland Village', 'Holland V'], dtype=object)

### Challenge 2: Clean the Data

**Tasks:**
1. Convert `revenue_raw` into a numeric column called `revenue_sgd`.
2. Replace the fake blanks in `notes` (`""`, `n/a`, `N.A.`, `-`) with `NaN`.
3. Mask the impossible values: negative takings, takings above 20,000, and ticket counts of zero or
   less.
4. Fill the resulting holes in `revenue_sgd` and `tickets` with each column's median — **in the right
   order**.
5. Standardise `outlet` to the four real café names, and `daypart` to Morning / Midday / Evening.
6. Verify: no impossible values left, and `outlet` has exactly four values.

In [63]:
clean_may = may.copy()  # copy another version clean_may

# 1. converrt revenue into numeric

clean_may["revenue_sgd"] = pd.to_numeric(
    clean_may["revenue_raw"].str.replace(r"[^0-9.\-]", "", regex=True), errors="coerce"
)

display(may.head())  # may record remain unchanged

display(clean_may)   # cleaning done in clean_may version

,outlet,date_text,daypart,revenue_raw,tickets,staff_on_shift,manager,notes
0,Raffles Place,01/05/2025,Morning,S$612.40,74.0,3.0,Aisha Rahman,
1,raffles place,01/05/2025,AM,318.75,39.0,2.0,aisha rahman,n/a
2,RAFFLES PLACE,02/05/2025,morning,-999,55.0,NaN,AISHA RAHMAN,N.A.
3,Raffles Pl.,02/05/2025,Midday,487.10,58.0,2.0,Aisha Rahman,-
4,Marina Bay,01/05/2025,Lunch,"S$1,204.60",141.0,5.0,Priya Nair,aircon down

,outlet,date_text,daypart,revenue_raw,tickets,staff_on_shift,manager,notes,revenue_sgd
0,Raffles Place,01/05/2025,Morning,S$612.40,74.0,3.0,Aisha Rahman,,612.40
1,raffles place,01/05/2025,AM,318.75,39.0,2.0,aisha rahman,n/a,318.75
2,RAFFLES PLACE,02/05/2025,morning,-999,55.0,NaN,AISHA RAHMAN,N.A.,-999.00
3,Raffles Pl.,02/05/2025,Midday,487.10,58.0,2.0,Aisha Rahman,-,487.10
4,Marina Bay,01/05/2025,Lunch,"S$1,204.60",141.0,5.0,Priya Nair,aircon down,1204.60
5,marina bay,01/05/2025,midday,296.55,36.0,2.0,priya nair,,296.55
6,Marina Bay,02/05/2025,Evening,,21.0,1.0,Priya Nair,-,NaN
7,Marina Bay,02/05/2025,PM,58000,112.0,4.0,Priya Nair,,58000.00
8,Tampines Mall,01/05/2025,evening,S$734.20,88.0,4.0,wei ming tan,n/a,734.20
9,tampines mall,02/05/2025,Morning,421.85,51.0,2.0,Wei Ming Tan,,421.85
10,Holland Village,01/05/2025,AM,S$389.90,NaN,2.0,DANIEL LIM,N.A.,389.90
11,Holland V,02/05/2025,Lunch,-999,-3.0,NaN,Daniel Lim,,-999.00

In [64]:
# 2. replae notes fake blanks -> real blanks (NaN), so .isna() tells the truth from here on.

clean_may["notes"] = clean_may["notes"].replace(["", "n/a", "N.A.", "-"], np.nan)

clean_may

,outlet,date_text,daypart,revenue_raw,tickets,staff_on_shift,manager,notes,revenue_sgd
0,Raffles Place,01/05/2025,Morning,S$612.40,74.0,3.0,Aisha Rahman,NaN,612.40
1,raffles place,01/05/2025,AM,318.75,39.0,2.0,aisha rahman,NaN,318.75
2,RAFFLES PLACE,02/05/2025,morning,-999,55.0,NaN,AISHA RAHMAN,NaN,-999.00
3,Raffles Pl.,02/05/2025,Midday,487.10,58.0,2.0,Aisha Rahman,NaN,487.10
4,Marina Bay,01/05/2025,Lunch,"S$1,204.60",141.0,5.0,Priya Nair,aircon down,1204.60
5,marina bay,01/05/2025,midday,296.55,36.0,2.0,priya nair,NaN,296.55
6,Marina Bay,02/05/2025,Evening,,21.0,1.0,Priya Nair,NaN,NaN
7,Marina Bay,02/05/2025,PM,58000,112.0,4.0,Priya Nair,NaN,58000.00
8,Tampines Mall,01/05/2025,evening,S$734.20,88.0,4.0,wei ming tan,NaN,734.20
9,tampines mall,02/05/2025,Morning,421.85,51.0,2.0,Wei Ming Tan,NaN,421.85
10,Holland Village,01/05/2025,AM,S$389.90,NaN,2.0,DANIEL LIM,NaN,389.90
11,Holland V,02/05/2025,Lunch,-999,-3.0,NaN,Daniel Lim,NaN,-999.00

In [65]:
# 3. mask the invalid values (find -> decide -> apply), revenue > 20,000 & ticket <= 0

clean_may["revenue_sgd"] = clean_may["revenue_sgd"].mask(
    (clean_may["revenue_sgd"] < 0) | (clean_may["revenue_sgd"] > 20000)
)
clean_may["tickets"] = clean_may["tickets"].mask(clean_may["tickets"] <= 0)

clean_may

# alternate method using where
# clean_may["revenue_sgd"] = clean_may["revenue_sgd"].where(clean_may["revenue_sgd"].between(0, 20000))
# clean_may["tickets"] = clean_may["tickets"].where(clean_may["tickets"] > 0)

,outlet,date_text,daypart,revenue_raw,tickets,staff_on_shift,manager,notes,revenue_sgd
0,Raffles Place,01/05/2025,Morning,S$612.40,74.0,3.0,Aisha Rahman,NaN,612.40
1,raffles place,01/05/2025,AM,318.75,39.0,2.0,aisha rahman,NaN,318.75
2,RAFFLES PLACE,02/05/2025,morning,-999,55.0,NaN,AISHA RAHMAN,NaN,NaN
3,Raffles Pl.,02/05/2025,Midday,487.10,58.0,2.0,Aisha Rahman,NaN,487.10
4,Marina Bay,01/05/2025,Lunch,"S$1,204.60",141.0,5.0,Priya Nair,aircon down,1204.60
5,marina bay,01/05/2025,midday,296.55,36.0,2.0,priya nair,NaN,296.55
6,Marina Bay,02/05/2025,Evening,,21.0,1.0,Priya Nair,NaN,NaN
7,Marina Bay,02/05/2025,PM,58000,112.0,4.0,Priya Nair,NaN,NaN
8,Tampines Mall,01/05/2025,evening,S$734.20,88.0,4.0,wei ming tan,NaN,734.20
9,tampines mall,02/05/2025,Morning,421.85,51.0,2.0,Wei Ming Tan,NaN,421.85
10,Holland Village,01/05/2025,AM,S$389.90,NaN,2.0,DANIEL LIM,NaN,389.90
11,Holland V,02/05/2025,Lunch,-999,NaN,NaN,Daniel Lim,NaN,NaN

In [ ]:
# 4. compute the medians and update NaN with median 
# replace invalid value to NaN before median computation to ensure accuracy

clean_may = clean_may.fillna({
    "revenue_sgd": clean_may["revenue_sgd"].median(),
    "tickets": clean_may["tickets"].median(),
    "staff_on_shift": clean_may["staff_on_shift"].median(),
})

clean_may

,outlet,date_text,daypart,revenue_raw,tickets,staff_on_shift,manager,notes,revenue_sgd
0,Raffles Place,01/05/2025,Morning,S$612.40,74.0,3.0,Aisha Rahman,NaN,612.400
1,raffles place,01/05/2025,AM,318.75,39.0,2.0,aisha rahman,NaN,318.750
2,RAFFLES PLACE,02/05/2025,morning,-999,55.0,2.0,AISHA RAHMAN,NaN,454.475
3,Raffles Pl.,02/05/2025,Midday,487.10,58.0,2.0,Aisha Rahman,NaN,487.100
4,Marina Bay,01/05/2025,Lunch,"S$1,204.60",141.0,5.0,Priya Nair,aircon down,1204.600
5,marina bay,01/05/2025,midday,296.55,36.0,2.0,priya nair,NaN,296.550
6,Marina Bay,02/05/2025,Evening,,21.0,1.0,Priya Nair,NaN,454.475
7,Marina Bay,02/05/2025,PM,58000,112.0,4.0,Priya Nair,NaN,454.475
8,Tampines Mall,01/05/2025,evening,S$734.20,88.0,4.0,wei ming tan,NaN,734.200
9,tampines mall,02/05/2025,Morning,421.85,51.0,2.0,Wei Ming Tan,NaN,421.850
10,Holland Village,01/05/2025,AM,S$389.90,56.5,2.0,DANIEL LIM,NaN,389.900
11,Holland V,02/05/2025,Lunch,-999,56.5,2.0,Daniel Lim,NaN,454.475

In [68]:
# 5. standardize outlet and daypart naming

outlet_map = {
    "Raffles Place": "Raffles Place", "raffles place": "Raffles Place",
    "RAFFLES PLACE": "Raffles Place", "Raffles Pl.": "Raffles Place",
    "Marina Bay": "Marina Bay", "marina bay": "Marina Bay", "Marina Bay ": "Marina Bay",
    "Tampines Mall": "Tampines Mall", "tampines mall": "Tampines Mall",
    "Holland Village": "Holland Village", "Holland V": "Holland Village",
}
daypart_map = {
    "Morning": "Morning", "morning": "Morning", "AM": "Morning",
    "Midday": "Midday", "midday": "Midday", "Lunch": "Midday",
    "Evening": "Evening", "evening": "Evening", "PM": "Evening",
}
clean_may["outlet_name"] = clean_may["outlet"].map(outlet_map)
clean_may["daypart"] = clean_may["daypart"].map(daypart_map)

clean_may

,outlet,date_text,daypart,revenue_raw,tickets,staff_on_shift,manager,notes,revenue_sgd,outlet_name
0,Raffles Place,01/05/2025,Morning,S$612.40,74.0,3.0,Aisha Rahman,NaN,612.400,Raffles Place
1,raffles place,01/05/2025,Morning,318.75,39.0,2.0,aisha rahman,NaN,318.750,Raffles Place
2,RAFFLES PLACE,02/05/2025,Morning,-999,55.0,2.0,AISHA RAHMAN,NaN,454.475,Raffles Place
3,Raffles Pl.,02/05/2025,Midday,487.10,58.0,2.0,Aisha Rahman,NaN,487.100,Raffles Place
4,Marina Bay,01/05/2025,Midday,"S$1,204.60",141.0,5.0,Priya Nair,aircon down,1204.600,Marina Bay
5,marina bay,01/05/2025,Midday,296.55,36.0,2.0,priya nair,NaN,296.550,Marina Bay
6,Marina Bay,02/05/2025,Evening,,21.0,1.0,Priya Nair,NaN,454.475,Marina Bay
7,Marina Bay,02/05/2025,Evening,58000,112.0,4.0,Priya Nair,NaN,454.475,Marina Bay
8,Tampines Mall,01/05/2025,Evening,S$734.20,88.0,4.0,wei ming tan,NaN,734.200,Tampines Mall
9,tampines mall,02/05/2025,Morning,421.85,51.0,2.0,Wei Ming Tan,NaN,421.850,Tampines Mall
10,Holland Village,01/05/2025,Morning,S$389.90,56.5,2.0,DANIEL LIM,NaN,389.900,Holland Village
11,Holland V,02/05/2025,Midday,-999,56.5,2.0,Daniel Lim,NaN,454.475,Holland Village

In [69]:
# 6. verify cleaning

print("unmapped outlets:", clean_may["outlet_name"].isna().sum())
print("unmapped dayparts:", clean_may["daypart"].isna().sum())
print("cafés:", clean_may["outlet_name"].nunique())
print("min revenue:", clean_may["revenue_sgd"].min(), "| max:", clean_may["revenue_sgd"].max())
print("min tickets:", clean_may["tickets"].min())

unmapped outlets: 0
unmapped dayparts: 0
cafés: 4
min revenue: 296.55 | max: 1204.6
min tickets: 21.0

### Challenge 3: Transform & Summarise

**Tasks:**
1. Convert `date_text` to a real datetime column called `date`. Careful: `01/05/2025` is 1 May here.
2. Clean the `manager` column so each manager's name appears exactly once, in Title Case.
3. Add a `shift_size` column with `pd.cut`: 0–350 `"Quiet"`, 350–700 `"Normal"`, 700–1500 `"Busy"`.
4. Build a summary table: one row per café, with total revenue, number of shifts and average revenue
   per shift, sorted by total revenue.

In [ ]:
# 1. dayfirst=True matters: without it, 01/05/2025 could be read as 5 January.

clean_may["date"] = pd.to_datetime(clean_may["date_text"], dayfirst=True)  # dayfirst=True -> 1st number is day

clean_may[['date_text', 'date']].head()

    date_text       date
0  01/05/2025 2025-05-01
1  01/05/2025 2025-05-01
2  02/05/2025 2025-05-02
3  02/05/2025 2025-05-02
4  01/05/2025 2025-05-01

In [ ]:
# 2. strip the spaces off the ENDS, squeeze the doubled spaces in the MIDDLE, then Title Case.
#    `\s+` means "one or more whitespace characters"; replacing them with a single space turns
#    "Priya  Nair" into "Priya Nair". `.str.strip()` alone would not have caught that one.

clean_may["manager"] = (
    clean_may["manager"].str.strip().str.replace(r"\s+", " ", regex=True).str.title()
)
print(clean_may["manager"].unique())

['Aisha Rahman' 'Priya Nair' 'Wei Ming Tan' 'Daniel Lim']

In [81]:
# 3. group into 3 bin size

clean_may["shift_size"] = pd.cut(
    clean_may["revenue_sgd"], bins=[0, 350, 700, 1500], labels=["Quiet", "Normal", "Busy"]
)
print(clean_may["shift_size"].value_counts())

Normal    8
Quiet     2
Busy      2
Name: shift_size, dtype: int64

In [82]:
# 4. summary table by café, with total revenue, number of shifts and average revenue per shift, sorted by total revenue.

may_summary = clean_may.groupby("outlet_name", observed=True).agg(
    revenue=("revenue_sgd", "sum"),
    shifts=("revenue_sgd", "size"),
    avg_shift=("revenue_sgd", "mean"),
).round(2).sort_values("revenue", ascending=False)

may_summary

                 revenue  shifts  avg_shift
outlet_name
Marina Bay       2410.10       4     602.52
Raffles Place    1872.72       4     468.18
Tampines Mall    1156.05       2     578.03
Holland Village   844.38       2     422.19

### 🏆 Stretch Challenge (optional)

Do the same audit on the **real** file, `data/cafe_june_raw.csv`, but for one outlet only:

1. Filter to Marina Bay (all three spellings) *before* cleaning. How would you do that safely?
2. Clean it and compute its total June revenue.
3. Export the result to CSV, reload it, and confirm the total and the row count survive the trip.
4. What comes back as a different **type** than it went out as, and why?

In [127]:
import pandas as pd
import numpy as np

# assignment-working location is same level as data folder, no need use "../data/cafe_june_raw.csv" to go 1 level up
june_raw = pd.read_csv("data/cafe_june_raw.csv") 

june_raw

,outlet,date_text,daypart,revenue_raw,tickets,items,staff_on_shift,manager,manager_email,notes
0,RAFFLES PLACE,01/06/2025,evening,S$78.38,9.0,13.0,1.0,Aisha Rahman,aisha.rahman@dailygrind.sg,NaN
1,Raffles Place,01/06/2025,Midday,205.21,20.0,30.0,2.0,Aisha Rahman,aisha.rahman@dailygrind.sg,NaN
2,raffles place,01/06/2025,AM,324.52,50.0,71.0,3.0,Aisha Rahman,aisha.rahman@dailygrind.sg,N.A.
3,Tampines Mall,01/06/2025,PM,615.79,61.0,90.0,4.0,wei ming tan,weiming.tan@dailygrind.sg,NaN
4,Tampines Mall,01/06/2025,Midday,932.35,82.0,119.0,5.0,wei ming tan,weiming.tan@dailygrind.sg,NaN
...,...,...,...,...,...,...,...,...,...,...
361,Marina Bay,30/06/2025,Midday,S$497.02,49.0,73.0,3.0,Priya Nair,priya.nair@dailygrind.sg,NaN
362,marina bay,30/06/2025,Morning,S$548.02,90.0,135.0,5.0,Priya Nair,priya.nair@dailygrind.sg,NaN
363,Holland V,30/06/2025,Evening,619.51,66.0,91.0,4.0,DANIEL LIM,daniel.lim@dailygrind.com.sg,NaN
364,Holland Village,30/06/2025,midday,515.76,50.0,75.0,3.0,DANIEL LIM,daniel.lim@dailygrind.com.sg,NaN
365,Holland V,30/06/2025,Morning,455.32,68.0,103.0,4.0,DANIEL LIM,daniel.lim@dailygrind.com.sg,NaN

In [128]:
# 1. filter marina bay outlets records and copy into a new file

display(june_raw["outlet"].value_counts())

# marina_outlet is a new variable created w/o adding new column to june_raw file
# .str.strip() ignore hidden space in marina bay naming
# .str.lower() ignore upper & lower cap variants (MARINA Bay, marina Bay etc)
marina_outlet = june_raw["outlet"].str.strip().str.lower() == "marina bay" 

# june_raw[marina_outlet] is boolean indexing tells pandas to keep the rows in june_raw where outlet = marina bay
marina = june_raw[marina_outlet].copy()

print("rows:", len(marina), "| spellings matched:", marina["outlet"].nunique())

#print("rows:", len(marina), "| Standardized spellings:", marina["outlet"].str.strip().str.lower().unique().tolist())

marina

Holland V          47
Holland Village    44
marina bay         36
Tampines  Mall     34
Marina Bay         31
tampines mall      30
Marina Bay         26
Tampines Mall      26
RAFFLES PLACE      23
Raffles Place      23
raffles place      23
Raffles Pl.        23
Name: outlet, dtype: int64

rows: 93 | spellings matched: 3

,outlet,date_text,daypart,revenue_raw,tickets,items,staff_on_shift,manager,manager_email,notes
6,Marina Bay,01/06/2025,Evening,S$67.72,7.0,10.0,1.0,Priya Nair,priya.nair@dailygrind.sg,NaN
7,Marina Bay,01/06/2025,midday,S$207.79,19.0,27.0,2.0,Priya Nair,priya.nair@dailygrind.sg,NaN
8,Marina Bay,01/06/2025,AM,S$280.20,40.0,59.0,NaN,Priya Nair,priya.nair@dailygrind.sg,NaN
18,marina bay,02/06/2025,Evening,173.74,18.0,28.0,2.0,Priya Nair,priya.nair@dailygrind.sg,NaN
19,Marina Bay,02/06/2025,midday,S$394.68,36.0,55.0,3.0,Priya Nair,NaN,N.A.
...,...,...,...,...,...,...,...,...,...,...
349,Marina Bay,29/06/2025,midday,S$154.99,15.0,22.0,2.0,Priya Nair,priya.nair@dailygrind.sg,NaN
350,Marina Bay,29/06/2025,morning,228.34,35.0,52.0,3.0,Priya Nair,priya.nair@dailygrind.sg,NaN
360,Marina Bay,30/06/2025,evening,170.03,18.0,26.0,2.0,Priya Nair,priya.nair@dailygrind.sg,NaN
361,Marina Bay,30/06/2025,Midday,S$497.02,49.0,73.0,3.0,Priya Nair,priya.nair@dailygrind.sg,NaN
362,marina bay,30/06/2025,Morning,S$548.02,90.0,135.0,5.0,Priya Nair,priya.nair@dailygrind.sg,NaN

In [ ]:
marina["revenue_sgd"] = pd.to_numeric(
    marina["revenue_raw"].str.replace(r"[^0-9.\-]", "", regex=True), errors="coerce"
)

bad_revenue_condition = (marina["revenue_sgd"] < 0) | (marina["revenue_sgd"] > 20000)

# display the rows that meet the condition for verification
display(marina[bad_revenue_condition])

# display duplicates
all_duplicates = marina[marina.duplicated(keep=False)] # show all duplicate rows
display(all_duplicates)

# marina[marina.duplicated()] -> only show duplicate once

,outlet,date_text,daypart,revenue_raw,tickets,items,staff_on_shift,manager,manager_email,notes,revenue_sgd
107,Marina Bay,09/06/2025,Morning,-999,76.0,113.0,4.0,Priya Nair,priya.nair@dailygrind.sg,NaN,-999.0
155,Marina Bay,13/06/2025,morning,98000,125.0,181.0,6.0,Priya Nair,priya.nair@dailygrind.sg,NaN,98000.0

,outlet,date_text,daypart,revenue_raw,tickets,items,staff_on_shift,manager,manager_email,notes,revenue_sgd
30,Marina Bay,03/06/2025,evening,S$193.08,22.0,31.0,2.0,Priya Nair,priya.nair@dailygrind.sg,NaN,193.08
31,Marina Bay,03/06/2025,Lunch,497.17,49.0,77.0,3.0,Priya Nair,priya.nair@dailygrind.sg,NaN,497.17
32,marina bay,03/06/2025,Morning,698.28,101.0,151.0,6.0,Priya Nair,priya.nair@dailygrind.sg,NaN,698.28
36,Marina Bay,03/06/2025,evening,S$193.08,22.0,31.0,2.0,Priya Nair,priya.nair@dailygrind.sg,NaN,193.08
37,Marina Bay,03/06/2025,Lunch,497.17,49.0,77.0,3.0,Priya Nair,priya.nair@dailygrind.sg,NaN,497.17
38,marina bay,03/06/2025,Morning,698.28,101.0,151.0,6.0,Priya Nair,priya.nair@dailygrind.sg,NaN,698.28

In [ ]:
# 2. cleaning and compute jun revenue
# remove 3 duplicate records, replace invalid revenue values to median, standardize date format

marina["revenue_sgd"] = pd.to_numeric(
    marina["revenue_raw"].str.replace(r"[^0-9.\-]", "", regex=True), errors="coerce"
)
marina = marina.drop_duplicates()
marina["revenue_sgd"] = marina["revenue_sgd"].mask(
    (marina["revenue_sgd"] < 0) | (marina["revenue_sgd"] > 20000)
)
marina["revenue_sgd"] = marina["revenue_sgd"].fillna(marina["revenue_sgd"].median())
marina["date"] = pd.to_datetime(marina["date_text"], dayfirst=True)

print(f"Marina Bay, June 2025: ${marina['revenue_sgd'].sum():,.2f} across {len(marina)} shifts")

marina

Marina Bay, June 2025: $32,058.17 across 90 shifts

/tmp/ipykernel_157828/3064943022.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  marina["revenue_sgd"] = marina["revenue_sgd"].mask(
/tmp/ipykernel_157828/3064943022.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  marina["revenue_sgd"] = marina["revenue_sgd"].fillna(marina["revenue_sgd"].median())
/tmp/ipykernel_157828/3064943022.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  marina["date"] = pd.to_datetime(marina["date_text"], dayfirst=True)

,outlet,date_text,daypart,revenue_raw,tickets,items,staff_on_shift,manager,manager_email,notes,revenue_sgd,date
6,Marina Bay,01/06/2025,Evening,S$67.72,7.0,10.0,1.0,Priya Nair,priya.nair@dailygrind.sg,NaN,67.72,2025-06-01
7,Marina Bay,01/06/2025,midday,S$207.79,19.0,27.0,2.0,Priya Nair,priya.nair@dailygrind.sg,NaN,207.79,2025-06-01
8,Marina Bay,01/06/2025,AM,S$280.20,40.0,59.0,NaN,Priya Nair,priya.nair@dailygrind.sg,NaN,280.20,2025-06-01
18,marina bay,02/06/2025,Evening,173.74,18.0,28.0,2.0,Priya Nair,priya.nair@dailygrind.sg,NaN,173.74,2025-06-02
19,Marina Bay,02/06/2025,midday,S$394.68,36.0,55.0,3.0,Priya Nair,NaN,N.A.,394.68,2025-06-02
...,...,...,...,...,...,...,...,...,...,...,...,...
349,Marina Bay,29/06/2025,midday,S$154.99,15.0,22.0,2.0,Priya Nair,priya.nair@dailygrind.sg,NaN,154.99,2025-06-29
350,Marina Bay,29/06/2025,morning,228.34,35.0,52.0,3.0,Priya Nair,priya.nair@dailygrind.sg,NaN,228.34,2025-06-29
360,Marina Bay,30/06/2025,evening,170.03,18.0,26.0,2.0,Priya Nair,priya.nair@dailygrind.sg,NaN,170.03,2025-06-30
361,Marina Bay,30/06/2025,Midday,S$497.02,49.0,73.0,3.0,Priya Nair,priya.nair@dailygrind.sg,NaN,497.02,2025-06-30
362,marina bay,30/06/2025,Morning,S$548.02,90.0,135.0,5.0,Priya Nair,priya.nair@dailygrind.sg,NaN,548.02,2025-06-30

In [135]:
# 3. export result to csv

june_mb = marina[[
    "date", "daypart", "tickets", "revenue_sgd",
]].sort_values(["date", "daypart"])

june_mb.to_csv("data/june_mb.csv", index=False)

june_mb.head()

         date  daypart  tickets  revenue_sgd
8  2025-06-01       AM     40.0       280.20
6  2025-06-01  Evening      7.0        67.72
7  2025-06-01   midday     19.0       207.79
20 2025-06-02       AM     96.0       615.53
18 2025-06-02  Evening     18.0       173.74